#pragma once

#define INVALID_EDGE_ID ((u16)(-1))
#define INVALID_COLUMN_ID ((u8)(-1))
#define INVALID_PROJECTILE_INDEX ((u8)(-1))

#define MAX_WALL_HITS_COUNT (1024*5)
#define MAX_GROUND_HITS_COUNT (1024*2)

#define MAX_PORTAL_DEPTH 32

#define DEFAULT_RENDER_MODE RenderMode_Beauty

#define CAST_SHADOWS       (1 << 0)
#define VOLUMETRIC_SHADOWS (1 << 1)
#define VOLUMETRIC         (1 << 2)
#define USE_ROUGHNESS_MAP  (1 << 3)
#define USE_AO_MAP         (1 << 4)
#define USE_NORMAL_MAP     (1 << 5)
#define USE_MAPS_MASK (USE_ROUGHNESS_MAP | USE_AO_MAP | USE_NORMAL_MAP)

#define MAX_POINT_LIGHTS 16
#define MAX_ENEMIES 4

#define PORTAL_FINAL_RADIUS 0.4f
#define PORTAL_INITIAL_RADIUS 0.1f
#define PORTAL_BREATHING_RANGE 0.04f
#define PORTAL_GROW_TIME 1.5f
#define PORTAL_GROW_RATE (1.0f / PORTAL_GROW_TIME)
#define PORTAL_GROW_RANGE (PORTAL_FINAL_RADIUS - PORTAL_INITIAL_RADIUS)
#define PORTAL_GROW_RADIUS (PORTAL_INITIAL_RADIUS + PORTAL_BREATHING_RANGE)
#define PORTAL_MAX_RADIUS (PORTAL_FINAL_RADIUS + PORTAL_BREATHING_RANGE)

#define MIP_LEVEL_0_COLOR BrightRed
#define MIP_LEVEL_1_COLOR BrightYellow
#define MIP_LEVEL_2_COLOR BrightGreen
#define MIP_LEVEL_3_COLOR BrightMagenta
#define MIP_LEVEL_4_COLOR BrightCyan
#define MIP_LEVEL_5_COLOR BrightBlue
#define MIP_LEVEL_6_COLOR BrightGrey
#define MIP_LEVEL_7_COLOR Grey
#define MIP_LEVEL_8_COLOR DarkGrey

#define UNTEXTURED_WALL_COLOR DarkGrey
#define UNTEXTURED_FLOOR_COLOR DarkYellow
#define UNTEXTURED_CEILING_COLOR DarkCyan

#define INITIAL_COLUMN_RADIUS 0.1f
#define BODY_RADIUS 0.2f
#define PROJECTILE_RADIUS 0.2f
#define PROJECTILE_SPEED 6.0f
